"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _showcase from './showcase.bones.json'
import _categories from './categories.bones.json'
import _faq from './faq.bones.json'
import _tweets from './tweets.bones.json'

registerBones({
  "showcase": _showcase,
  "categories": _categories,
  "faq": _faq,
  "tweets": _tweets,
})
